FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
EXPOSE 3000
RUN ls -la /app/node_modules/.bin/
# CMD ["./node_modules/.bin/next", "dev", "--hostname", "0.0.0.0"]