FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential gcc curl && rm -rf /var/lib/apt/lists/*

# ---------------------------
# 1) Install base dependencies
# ---------------------------

COPY requirements/db_migrate.txt requirements/db_migrate.txt
RUN pip install --no-cache-dir -r requirements/db_migrate.txt

ENV PYTHONPATH=/app