"""Descripton column nullable

Revision ID: 0898bb0c257b
Revises: bb89b4389642
Create Date: 2025-11-30 14:32:44.634349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0898bb0c257b'
down_revision: Union[str, Sequence[str], None] = 'bb89b4389642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'description')
    # ### end Alembic commands ###
