"""added a unique constraint to transcript_utterances table

Revision ID: 355b253bcb29
Revises: 0898bb0c257b
Create Date: 2025-12-10 23:41:14.177124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355b253bcb29'
down_revision: Union[str, Sequence[str], None] = '0898bb0c257b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_utterance_transcript_start', 'transcript_utterances', ['transcript_id', 'start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_utterance_transcript_start', 'transcript_utterances', type_='unique')
    # ### end Alembic commands ###
