"""added category fields to podcast model

Revision ID: 361e8da95645
Revises: a41cca05294e
Create Date: 2025-12-25 09:15:20.746010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361e8da95645'
down_revision: Union[str, Sequence[str], None] = 'a41cca05294e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add category_1 as nullable first
    op.add_column('podcasts', sa.Column('category_1', sa.String(), nullable=True))
    op.add_column('podcasts', sa.Column('category_2', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE podcasts SET category_1 = 'technology' WHERE category_1 IS NULL")
    
    # Now make category_1 NOT NULL
    op.alter_column('podcasts', 'category_1', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'category_2')
    op.drop_column('podcasts', 'category_1')
    # ### end Alembic commands ###
