"""added itunes ratings, number of ratings and popularity score

Revision ID: a41cca05294e
Revises: 355b253bcb29
Create Date: 2025-12-24 18:05:39.769269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41cca05294e'
down_revision: Union[str, Sequence[str], None] = '355b253bcb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('itunes_rating', sa.Float(), nullable=True))
    op.add_column('podcasts', sa.Column('itunes_number_of_ratings', sa.Integer(), nullable=True))
    # Add popularity_score as nullable first
    op.add_column('podcasts', sa.Column('popularity_score', sa.Float(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE podcasts SET popularity_score = 0.0 WHERE popularity_score IS NULL")
    # Now make it NOT NULL
    op.alter_column('podcasts', 'popularity_score', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'popularity_score')
    op.drop_column('podcasts', 'itunes_number_of_ratings')
    op.drop_column('podcasts', 'itunes_rating')
    # ### end Alembic commands ###
